const ArrayData = [
    {
        id: 1,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '2 200₽',
        cardPlace: 'Санкт Петербург',
        CardDate: '13:49',
    },
    {
        id: 2,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '5 000₽',
        cardPlace: 'Ростлв-на-Дону',
        CardDate: '00:23',
    },
    {
        id: 3,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '300₽',
        cardPlace: 'Москва',
        CardDate: '07:44',
    },
    {
        id: 4,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '200₽',
        cardPlace: 'Тверь',
        CardDate: '19:34',
    },
    {
        id: 5,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '220₽',
        cardPlace: 'Казань',
        CardDate: '15:13',
    },
    {
        id: 6,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '22 000₽',
        cardPlace: 'Омск',
        CardDate: '12:10',
    },
    {
        id: 7,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '3 000₽',
        cardPlace: 'Новосибирск',
        CardDate: '23:15',
    },
    {
        id: 8,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '890₽',
        cardPlace: 'Санкт Петербург',
        CardDate: '10:00',
    },
    {
        id: 9,
        img: '',
        cardTitle: 'Ракетка для большого тенниса Triumph Pro ST',
        cardPrice: '6 100₽',
        cardPlace: 'Тверь',
        CardDate: '11:45',
    },
];

export default ArrayData;
